<?php

/**
 * @file
 *  Link general privatemsg module functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function pm_service_perm() {
  return array(
    'get private messages remotely', 'send private messages remotely'
  );
}

/**
 * Implementation of hook_service().
 */
function pm_service_service() {
  return array(
    // pm.get
    array(
      '#method'           => 'pm.get',
      '#callback'         => 'pm_service_get',
      '#access arguments' => array('get private messages remotely'),
      '#file'             => array('file' => 'inc', 'module' => 'pm_service'),
      '#args'             => array(
        array(
          '#name'         => 'uid',
          '#type'         => 'int',
          '#description'  => t('A user ID.'),
        ),
        array(
          '#name'         => 'type',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('The type of messages to retrieve. Can be inbox or sent.')
        ),
        array(
          '#name'         => 'load_full',
          '#type'         => 'boolean',
          '#optional'     => TRUE,
          '#description'  => t('A boolean to indicate whether to load the full message or not.')
        ),
        array(
          '#name'           => 'offset',
          '#type'           => 'int',
          '#optional'       => TRUE,
          '#description'    => t('An offset integer for paging.')
        ),
        array(
          '#name'           => 'limit',
          '#type'           => 'int',
          '#optional'       => TRUE,
          '#description'    => t('A limit integer for paging.')
        ),
      ),
      '#return'           => 'array',
      '#help'             => t('Get a users private messages.')
    ),
    // pm.getUnreadCount
    array(
      '#method'           => 'pm.unreadCount',
      '#callback'         => 'pm_service_unread_count',
      '#access arguments' => array('get private messages remotely'),
      '#file'             => array('file' => 'inc', 'module' => 'pm_service'),
      '#args'             => array(
        array(
          '#name'         => 'uid',
          '#type'         => 'int',
          '#description'  => t('A user ID.'),
        ),
      ),
      '#return'           => 'int',
      '#help'             => t('Get a users private messages unread count.')
    ),
    // pm.send
    array(
      '#method'           => 'pm.send',
      '#callback'         => 'pm_service_send',
      '#access arguments' => array('send private messages remotely'),
      '#file'             => array('file' => 'inc', 'module' => 'pm_service'),
      '#args'             => array(
        array(
          '#name'         => 'author',
          '#type'         => 'int',
          '#description'  => t('A user ID of the author of the message.'),
        ),
        array(
          '#name'         => 'recipients',
          '#type'         => 'string',
          '#description'  => t('A comma separated list of recipients usernames.'),
        ),
        array(
          '#name'         => 'subject',
          '#type'         => 'string',
          '#description'  => t('A message subject.'),
        ),
        array(
          '#name'         => 'body',
          '#type'         => 'string',
          '#optional'     => TRUE,
          '#description'  => t('A message body.'),
        ),
        array(
          '#name'         => 'thread_id',
          '#type'         => 'int',
          '#optional'     => TRUE,
          '#description'  => t('A thread ID if this is an already existing message, otherwise leave blank for a new message.'),
        ),
      ),
      '#return'           => 'bool',
      '#help'             => t('Returns TRUE if the message sending was a success.')
    ),
  );
}