<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 预约门诊类型
 */
define('SBQ_CENTER_RESERVATION_TYPE_OUTPATIMENT', 0);
/**
 * 预约电话类型
 */
define('SBQ_CENTER_RESERVATION_TYPE_PHONE', 1);
/**
 * 预约表单id
 */
define('SBQ_CENTER_RESERVATION_NODE_ID', 21784);

/**
 * hook menu
 */
function sbq_center_reservation_menu() {
  $items['node/%/reservation/%'] = array(
      'page callback' => 'sbq_center_reservation',
      'page arguments' => array( 1, 3 ),
      'access callback' => 'sbq_center_reservation_access',
      'access arguments' => array( 'form', NULL),
      'file' => 'sbq_center_reservation.inc',
      'type' => MENU_CALLBACK,
  );

  return $items;
}
         
function sbq_center_reservation_access($type, $account = NULL) {
  return TRUE;
}

/*
 * hook_form_alter
 */

//function sbq_center_reservation_form_alter(&$form, $form_state, $form_id) {
//  if (strpos($form_id, 'webform_client_form_') !== FALSE) {
//    $nid = str_replace('webform_client_form_', '', $form_id);
//    if ($nid == SBQ_CENTER_RESERVATION_NODE_ID) {
//      if ($sbq_center = sbq_center_get_center()) {
////        $form['submitted']['sbq_center_id']['#value'] = $sbq_center->nid;
////        $form['submitted']['sbq_center_formcategory']['#value'] = SBQ_CENTER_RESERVATION_TYPE_OUTPATIMENT;
//      }
//    }
//  }
//}

/**
 * get sbq center reservation form only in sbq center page true running
 * @return type
 */
//function sbq_center_reservation_form(&$form, $form_state, $sbq_center_reservation_type) {
//  if ($sbq_center = sbq_center_get_center()) {
//    $form = &drupal_get_form('webform_client_form_' . SBQ_CENTER_RESERVATION_NODE_ID, node_load(SBQ_CENTER_RESERVATION_NODE_ID), array());
//    $form['submitted']['sbq_center_id']['#value'] = $sbq_center->nid;
//    $form['submitted']['sbq_center_formcategory']['#value'] = $sbq_center_reservation_type;
//  }
//  dpm($sbq_center);
//  return $form;
//}
